const bcrypt = require("bcrypt");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("lutadores").del();
  await knex("usuarios").del();

  const senhaHash = await bcrypt.hash("senha123", 10);

  const usuarios = await knex("usuarios")
    .insert([
      { email: "joao.silva@email.com", senha: senhaHash },
      { email: "pedro.santos@email.com", senha: senhaHash },
      { email: "lucas.oliveira@email.com", senha: senhaHash },
      { email: "gabriel.souza@email.com", senha: senhaHash },
      { email: "mateus.lima@email.com", senha: senhaHash },
      { email: "rafael.costa@email.com", senha: senhaHash },
      { email: "andre.ferreira@email.com", senha: senhaHash },
      { email: "thiago.alves@email.com", senha: senhaHash },
      { email: "bruno.rodrigues@email.com", senha: senhaHash },
      { email: "felipe.martins@email.com", senha: senhaHash },
      { email: "carlos.pereira@email.com", senha: senhaHash },
      { email: "vinicius.carvalho@email.com", senha: senhaHash },
      { email: "rodrigo.gomes@email.com", senha: senhaHash },
      { email: "daniel.nascimento@email.com", senha: senhaHash },
      { email: "gustavo.araújo@email.com", senha: senhaHash },
      { email: "henrique.barbosa@email.com", senha: senhaHash },
      { email: "leandro.ribeiro@email.com", senha: senhaHash },
      { email: "marcelo.tavares@email.com", senha: senhaHash },
      { email: "fabio.mendes@email.com", senha: senhaHash },
      { email: "alex.cunha@email.com", senha: senhaHash },
    ])
    .returning("id_usuario");

  const ids = usuarios.map((u) => u.id_usuario ?? u);

  await knex("lutadores").insert([
    {
      nome: "João Silva",
      cidade: "São Paulo",
      estado: "SP",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 84.0,
      modalidades: JSON.stringify(["MMA", "Muay Thai", "Jiu Jitsu"]),
      id_usuario: ids[0],
    },
    {
      nome: "Pedro Santos",
      cidade: "Rio de Janeiro",
      estado: "RJ",
      img: "https://www.claro.com.br/files/104379/860x1440/289e27821f/lutador-brasileiro-alex-poatan-ufc-2024.png/m/filters:quality(75)",
      peso: 70.3,
      modalidades: JSON.stringify(["Jiu Jitsu"]),
      id_usuario: ids[1],
    },
    {
      nome: "Lucas Oliveira",
      cidade: "Curitiba",
      estado: "PR",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 93.0,
      modalidades: JSON.stringify(["Karatê", "MMA", "Judô"]),
      id_usuario: ids[2],
    },
    {
      nome: "Gabriel Souza",
      cidade: "Salvador",
      estado: "BA",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 77.1,
      modalidades: JSON.stringify(["Capoeira", "MMA"]),
      id_usuario: ids[3],
    },
    {
      nome: "Mateus Lima",
      cidade: "Fortaleza",
      estado: "CE",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 120.0,
      modalidades: JSON.stringify(["Jiu Jitsu", "MMA", "Wrestling"]),
      id_usuario: ids[4],
    },
    {
      nome: "Rafael Costa",
      cidade: "Manaus",
      estado: "AM",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 108.0,
      modalidades: JSON.stringify(["Boxe"]),
      id_usuario: ids[5],
    },
    {
      nome: "André Ferreira",
      cidade: "Belo Horizonte",
      estado: "MG",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 84.0,
      modalidades: JSON.stringify(["Boxe", "MMA", "Muay Thai"]),
      id_usuario: ids[6],
    },
    {
      nome: "Thiago Alves",
      cidade: "Recife",
      estado: "PE",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 77.1,
      modalidades: JSON.stringify(["Muay Thai", "Boxe"]),
      id_usuario: ids[7],
    },
    {
      nome: "Bruno Rodrigues",
      cidade: "Porto Alegre",
      estado: "RS",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 84.0,
      modalidades: JSON.stringify(["Jiu Jitsu", "Wrestling", "MMA"]),
      id_usuario: ids[8],
    },
    {
      nome: "Felipe Martins",
      cidade: "Brasília",
      estado: "DF",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 93.0,
      modalidades: JSON.stringify(["Muay Thai", "MMA"]),
      id_usuario: ids[9],
    },
    {
      nome: "Carlos Pereira",
      cidade: "São Paulo",
      estado: "SP",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 93.0,
      modalidades: JSON.stringify(["Muay Thai", "MMA", "Boxe", "Judô"]),
      id_usuario: ids[10],
    },
    {
      nome: "Vinícius Carvalho",
      cidade: "Natal",
      estado: "RN",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 70.3,
      modalidades: JSON.stringify(["Jiu Jitsu", "MMA"]),
      id_usuario: ids[11],
    },
    {
      nome: "Rodrigo Gomes",
      cidade: "Goiânia",
      estado: "GO",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 77.1,
      modalidades: JSON.stringify(["Wrestling", "MMA", "Judô"]),
      id_usuario: ids[12],
    },
    {
      nome: "Daniel Nascimento",
      cidade: "Belém",
      estado: "PA",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 70.3,
      modalidades: JSON.stringify(["Wrestling"]),
      id_usuario: ids[13],
    },
    {
      nome: "Gustavo Araújo",
      cidade: "Florianópolis",
      estado: "SC",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 77.1,
      modalidades: JSON.stringify(["Jiu Jitsu", "Wrestling", "MMA", "Judô"]),
      id_usuario: ids[14],
    },
    {
      nome: "Henrique Barbosa",
      cidade: "Campinas",
      estado: "SP",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 70.3,
      modalidades: JSON.stringify(["Muay Thai", "Boxe", "MMA"]),
      id_usuario: ids[15],
    },
    {
      nome: "Leandro Ribeiro",
      cidade: "Santos",
      estado: "SP",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 65.8,
      modalidades: JSON.stringify(["Capoeira", "Jiu Jitsu"]),
      id_usuario: ids[16],
    },
    {
      nome: "Marcelo Tavares",
      cidade: "Vitória",
      estado: "ES",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 120.0,
      modalidades: JSON.stringify(["Judô", "MMA", "Wrestling", "Jiu Jitsu"]),
      id_usuario: ids[17],
    },
    {
      nome: "Fábio Mendes",
      cidade: "São Luís",
      estado: "MA",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 66.0,
      modalidades: JSON.stringify(["Judô"]),
      id_usuario: ids[18],
    },
    {
      nome: "Alex Cunha",
      cidade: "Maceió",
      estado: "AL",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 93.0,
      modalidades: JSON.stringify(["MMA", "Muay Thai", "Boxe",  "Jiu Jitsu"]),
      id_usuario: ids[19],
    },
  ]);
};