const bcrypt = require("bcrypt");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("lutadores").del();
  await knex("usuarios").del();

  const senhaHash = await bcrypt.hash("senha123", 10);

  const usuarios = await knex("usuarios")
    .insert([
      { email: "joao.silva@email.com", senha: senhaHash },
      { email: "pedro.santos@email.com", senha: senhaHash },
      { email: "lucas.oliveira@email.com", senha: senhaHash },
      { email: "gabriel.souza@email.com", senha: senhaHash },
      { email: "mateus.lima@email.com", senha: senhaHash },
      { email: "rafael.costa@email.com", senha: senhaHash },
      { email: "andre.ferreira@email.com", senha: senhaHash },
      { email: "thiago.alves@email.com", senha: senhaHash },
      { email: "bruno.rodrigues@email.com", senha: senhaHash },
      { email: "felipe.martins@email.com", senha: senhaHash },
      { email: "carlos.pereira@email.com", senha: senhaHash },
      { email: "vinicius.carvalho@email.com", senha: senhaHash },
      { email: "rodrigo.gomes@email.com", senha: senhaHash },
      { email: "daniel.nascimento@email.com", senha: senhaHash },
      { email: "gustavo.araújo@email.com", senha: senhaHash },
      { email: "henrique.barbosa@email.com", senha: senhaHash },
      { email: "leandro.ribeiro@email.com", senha: senhaHash },
      { email: "marcelo.tavares@email.com", senha: senhaHash },
      { email: "fabio.mendes@email.com", senha: senhaHash },
      { email: "alex.cunha@email.com", senha: senhaHash },
    ])
    .returning("id_usuario");

  const ids = usuarios.map((u) => u.id_usuario ?? u);

  await knex("lutadores").insert([
    {
      nome: "João Silva",
      cidade: "São Paulo",
      estado: "SP",
      img: "https://ufc.com/images/styles/background_image_sm/s3/2023-10/102623-hero-alex-pereira_GettyImages-1579885807.jpg?h=d1cb525d&itok=32lc3-ct",
      peso: 84.0,
      modalidades: JSON.stringify(["MMA", "Muay Thai", "Jiu Jitsu"]),
      id_usuario: ids[0],
    },
    {
      nome: "Pedro Santos",
      cidade: "Rio de Janeiro",
      estado: "RJ",
      img: "https://www.claro.com.br/files/104379/860x1440/289e27821f/lutador-brasileiro-alex-poatan-ufc-2024.png/m/filters:quality(75)",
      peso: 70.3,
      modalidades: JSON.stringify(["Jiu Jitsu"]),
      id_usuario: ids[1],
    },
    {
      nome: "Lucas Oliveira",
      cidade: "Campinas",
      estado: "SP",
      img: "https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2026/01/Themba-Gorimbo-e1769530253115.jpg?w=419&h=283&crop=0",
      peso: 93.0,
      modalidades: JSON.stringify(["Karatê", "MMA", "Judô"]),
      id_usuario: ids[2],
    },
    {
      nome: "Gabriel Souza",
      cidade: "Niterói",
      estado: "RJ",
      img: "https://lncimg.lance.com.br/cdn-cgi/image/width=950,quality=75,fit=pad,format=webp/uploads/2023/02/13/63ea57f3cf633.jpeg",
      peso: 77.1,
      modalidades: JSON.stringify(["Capoeira", "MMA"]),
      id_usuario: ids[3],
    },
    {
      nome: "Mateus Lima",
      cidade: "Santos",
      estado: "SP",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDHXeZ4THiietC0ckTg7zetEx9gEI06PcE1A&s",
      peso: 120.0,
      modalidades: JSON.stringify(["Jiu Jitsu", "MMA", "Wrestling"]),
      id_usuario: ids[4],
    },
    {
      nome: "Rafael Costa",
      cidade: "Duque de Caxias",
      estado: "RJ",
      img: "https://newr7-r7-prod.web.arc-cdn.net/resizer/v2/YCUON3SV4BJV3JNBKRN4GBZU7I.jpg?auth=d7b223368e7c67b55d4956bd3dc221cb5287964e87401a52e54399d88202f25e&width=591&height=597",
      peso: 108.0,
      modalidades: JSON.stringify(["Boxe"]),
      id_usuario: ids[5],
    },
    {
      nome: "André Ferreira",
      cidade: "Guarulhos",
      estado: "SP",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT080RNDmdbsD2t1wlOhwzZuwd4EWT13KKduA&s",
      peso: 84.0,
      modalidades: JSON.stringify(["Boxe", "MMA", "Muay Thai"]),
      id_usuario: ids[6],
    },
    {
      nome: "Thiago Alves",
      cidade: "Petrópolis",
      estado: "RJ",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzQgMyL5zy_zI-Jx7rQgnzrmwvEUQD6CMH2Q&s",
      peso: 77.1,
      modalidades: JSON.stringify(["Muay Thai", "Boxe"]),
      id_usuario: ids[7],
    },
    {
      nome: "Bruno Rodrigues",
      cidade: "São Bernardo do Campo",
      estado: "SP",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVLBUpJSPgyTIR7jHejKahkq1LSzgbeHneMA&s",
      peso: 84.0,
      modalidades: JSON.stringify(["Jiu Jitsu", "Wrestling", "MMA"]),
      id_usuario: ids[8],
    },
    {
      nome: "Felipe Martins",
      cidade: "Nova Iguaçu",
      estado: "RJ",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa8rnq5SQ167kWNn_3TNYejUfaInKu-fftzg&s",
      peso: 93.0,
      modalidades: JSON.stringify(["Muay Thai", "MMA"]),
      id_usuario: ids[9],
    },
    {
      nome: "Carlos Pereira",
      cidade: "São Paulo",
      estado: "SP",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr5j_0-mYph4yJ08eqxYBffn6cIGlOXAhcmg&s",
      peso: 93.0,
      modalidades: JSON.stringify(["Muay Thai", "MMA", "Boxe", "Judô"]),
      id_usuario: ids[10],
    },
    {
      nome: "Vinícius Carvalho",
      cidade: "São Gonçalo",
      estado: "RJ",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd4t5iKxIpaW7fHyWLoAEmq63AEb9OvQS5sA&s",
      peso: 70.3,
      modalidades: JSON.stringify(["Jiu Jitsu", "MMA"]),
      id_usuario: ids[11],
    },
    {
      nome: "Rodrigo Gomes",
      cidade: "Osasco",
      estado: "SP",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVP10JTzobIIm2icGpnlKb7YMnznmkEq4PaQ&s",
      peso: 77.1,
      modalidades: JSON.stringify(["Wrestling", "MMA", "Judô"]),
      id_usuario: ids[12],
    },
    {
      nome: "Daniel Nascimento",
      cidade: "Cabo Frio",
      estado: "RJ",
      img: "https://media.gettyimages.com/id/2238994939/pt/foto/las-vegas-nevada-alex-pereira-of-brazil-poses-on-the-scale-during-the-ufc-320-official-weigh.jpg?s=612x612&w=0&k=20&c=KR3T-Amfokbh9d1mIMRR9tamuL-16XbtMOYA5U7yBU0=",
      peso: 70.3,
      modalidades: JSON.stringify(["Wrestling"]),
      id_usuario: ids[13],
    },
    {
      nome: "Gustavo Araújo",
      cidade: "Santo André",
      estado: "SP",
      img: "https://media.gettyimages.com/id/2280951315/pt/foto/washington-dc-alex-pereira-poses-for-a-portrait-during-a-ufc-photo-session-on-june-10-2026-in.jpg?s=612x612&w=0&k=20&c=B_hKOIVrtUNgNgAe2-eeMekldp32qf1eexJ5ZukP1gE=",
      peso: 77.1,
      modalidades: JSON.stringify(["Jiu Jitsu", "Wrestling", "MMA", "Judô"]),
      id_usuario: ids[14],
    },
    {
      nome: "Henrique Barbosa",
      cidade: "Campinas",
      estado: "SP",
      img: "https://media.gettyimages.com/id/2148456417/pt/foto/las-vegas-nevada-alex-pereira-of-brazil-poses-on-the-scale-during-the-ufc-300-ceremonial-weigh.jpg?s=612x612&w=0&k=20&c=aSjyzmrdVyI7nilncYB8iw8I0vyg6ZfkzRnpeURse_o=",
      peso: 70.3,
      modalidades: JSON.stringify(["Muay Thai", "Boxe", "MMA"]),
      id_usuario: ids[15],
    },
    {
      nome: "Leandro Ribeiro",
      cidade: "Volta Redonda",
      estado: "RJ",
      img: "https://media.gettyimages.com/id/1146196410/pt/foto/black-fight-sport-athlete-shadow-boxing.jpg?s=612x612&w=0&k=20&c=ExWV6fyUaGyJ7n-FOdDIKEn-TD5Wmh_eASHnJmx9rCI=",
      peso: 65.8,
      modalidades: JSON.stringify(["Capoeira", "Jiu Jitsu"]),
      id_usuario: ids[16],
    },
    {
      nome: "Marcelo Tavares",
      cidade: "São José dos Campos",
      estado: "SP",
      img: "https://media.gettyimages.com/id/2281630813/pt/foto/washington-dc-ilia-topuria-of-spain-reacts-to-the-end-of-the-round-in-the-ufc-lightweight.jpg?s=612x612&w=0&k=20&c=-Z-ZlWmLIOj9-gsrPmOgdKyu7bA-fQul8uLunRhwojY=",
      peso: 120.0,
      modalidades: JSON.stringify(["Judô", "MMA", "Wrestling", "Jiu Jitsu"]),
      id_usuario: ids[17],
    },
    {
      nome: "Fábio Mendes",
      cidade: "Teresópolis",
      estado: "RJ",
      img: "https://media.gettyimages.com/id/154692803/pt/foto/san-jose-ca-wanderlei-silva-poses-for-a-portrait-on-november-16-2011-in-san-jose-california.jpg?s=612x612&w=0&k=20&c=QPzzaSdfpYQrhJtKlA_ElNRxOUQoTiyoTFXLEM7ln80=",
      peso: 66.0,
      modalidades: JSON.stringify(["Judô"]),
      id_usuario: ids[18],
    },
    {
      nome: "Alex Cunha",
      cidade: "Ribeirão Preto",
      estado: "SP",
      img: "https://media.gettyimages.com/id/2151003706/pt/foto/rio-de-janeiro-brazil-jose-aldo-poses-for-a-portrait-during-a-ufc-photo-session-on-may-1-2024.jpg?s=612x612&w=0&k=20&c=QucECLsevAD7cx5kFUlpn0_XJRcNgYcYiph_35joi6g=",
      peso: 93.0,
      modalidades: JSON.stringify(["MMA", "Muay Thai", "Boxe", "Jiu Jitsu"]),
      id_usuario: ids[19],
    },
  ]);
};